name: "Report a bug 🐞"
description: Create a new Bug
title: "[BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: "About Bug"
      description: Tell us more about the bug
      placeholder: "Write about the idea in detail, about how it will be useful and which problem would it solve"
    validations:
      required: true
  - type: textarea
    id: user-agent
    attributes:
      label: "User agent"
      description: Write your solution that could solve this feature request
      placeholder: "Write about the hypothetical solution you propose"
    validations:
      required: false
  - type: textarea
    id: image-proxy
    attributes:
      label: "Image proxy"
      description: Common issues that you think is relevant to this feature request
      placeholder: "#Issues IDs"
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: Write the facts or additional information that you think should be considered for the solution.
      placeholder: A few specific words would be enough.
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: "Any additional info"
      description: What questions still remain unresolved ?
      placeholder: Identify any unresolved issues.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Terms & Conditions
      description: By submitting this issue, I agree to be contacted back
      options:
        - label: whatever
          required: true
