name: Feature 🐞
description: Request a feature
type: bug
projects: ['podman-desktop/4']

body:
  - type: markdown
    attributes:
      value: |
        Before opening a feature request, please search for the behaviour in the existing issues.

        ---

        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.

  - type: textarea
    id: feature-title
    attributes:
      label: Feature title
      description: title?
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: What happened?
    validations:
      required: true

  - type: input
    id: user-agent
    attributes:
      label: user agent
      description: 'Which operating system are you on? Please provide the version as well. If you are on a Mac, please specify Apple silicon or Intel.'
      placeholder: 'macOS Ventura 13.4 (Arm), Windows 11'
    validations:
      required: true

  - type: dropdown
    id: install
    attributes:
      label: Installation Method
      description: 'How did you install Podman Desktop?'
      options:
        - 'Installer from website/GitHub releases'
        - 'Brew (macOS)'
        - 'Chocolatey (Windows)'
        - 'Flathub (Linux)'
        - 'Scoop (Windows)'
        - 'Winget (Windows)'
        - 'Other'

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots here.
