name: Feature 🐞
description: Request a feature
type: feature

body:
  - type: markdown
    attributes:
      value: |
        Before opening a feature request, please search for the behaviour in the existing issues.

        ---

        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: What happened?
    validations:
      required: true

  - type: dropdown
    id: install
    attributes:
      label: Installation Method
      description: 'How did you install Podman Desktop?'
      options:
        - 'Installer from website/GitHub releases'
        - 'Brew (macOS)'
        - 'Chocolatey (Windows)'
        - 'Flathub (Linux)'
        - 'Scoop (Windows)'
        - 'Winget (Windows)'
        - 'Other'

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots here.
