# FROM quay.io/konflux_ui_qe/konflux-ui-tests-base:5.8.0

# RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
#     install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# RUN wget "https://github.com/sigstore/cosign/releases/download/v2.4.0/cosign-linux-amd64" && \
#     mv cosign-linux-amd64 /usr/local/bin/cosign && \
#     chmod +x /usr/local/bin/cosign

FROM node:lts-alpine

USER node:0
RUN ls -la
COPY --chown=node:root --chmod=775 . /tmp/app-root

# # Copy source files
# COPY --chown=node:root --chmod=775 @types /tmp/app-root/@types
# COPY --chown=node:root --chmod=775 public /tmp/app-root/public
# COPY --chown=node:root --chmod=775 src /tmp/app-root/src
# COPY --chown=node:root --chmod=775 package.json /tmp/app-root/package.json
# COPY --chown=node:root --chmod=775 tsconfig.json /tmp/app-root/tsconfig.json
# COPY --chown=node:root --chmod=775 webpack.config.js /tmp/app-root/webpack.config.js
# COPY --chown=node:root --chmod=775 webpack.instrumented.config.js /tmp/app-root/webpack.instrumented.config.js
# COPY --chown=node:root --chmod=775 webpack.prod.config.js /tmp/app-root/webpack.prod.config.js
# COPY --chown=node:root --chmod=775 yarn.lock /tmp/app-root/yarn.lock
# COPY --chown=node:root --chmod=775 aliases.config.js /tmp/app-root/aliases.config.js
# Note: .swcrc is not needed for instrumented build as we use babel-loader

RUN cd /tmp/app-root/ && \
    ls -la && \
    yarn install
RUN cd /tmp/app-root/ && \
    yarn build:instrumented

COPY --chown=node:root --chmod=775 ./e2e-tests /tmp/app-root/e2e

RUN cd /tmp/app-root/e2e && \
    umask 0002 && \
    npm i && \
    node_modules/.bin/cypress install && \
    mkdir -p /tmp/app-root/e2e/artifacts && \
    chmod -R a+rwx /tmp/app-root/e2e/artifacts ${CYPRESS_CACHE_FOLDER}

# Label to identify this as an instrumented image
LABEL io.konflux.coverage.instrumented="true" \
      io.konflux.coverage.provider="istanbul-v8"

WORKDIR /tmp/src
COPY --chown=node:root --chmod=775 ./e2e-tests/entrypoint.sh /tmp/src/e2e

ENTRYPOINT ["/tmp/app-root/e2e/entrypoint.sh"]
CMD [""]
