apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-local
spec:
  steps:
    - name: run-podman
      image: quay.io/konflux-ci/tekton-integration-catalog/utils:latest
      onError: continue
      workingDir: /var/workdir
      script: |
        #!/bin/sh
        ls
        echo "installing docker"
        curl -fsSL https://get.docker.com/rootless | sh
        systemctl --user start docker
        systemctl --user enable docker
        loginctl enable-linger $(whoami)
        systemctl --user status docker
        docker info