---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-e2e-konflux-ui
  labels:
    konflux-ci/kind: 'true'
    app.kubernetes.io/version: '0.2'
    upstream-usable: 'true'
  annotations:
    tekton.dev/pipelines.minVersion: '0.44.x'
    tekton.dev/tags: konflux
spec:
  description: |
    This task performs a full Konflux CI deployment. It clones the specified Git repository,
    checks out the desired branch, and runs deployment scripts using a kubeconfig retrieved from
    a Kubernetes secret. It is intended for use in OpenShift Pipelines or other Tekton environments.

  params:
    - name: cluster-access-secret
      description: Name of the Kubernetes Secret that contains the kubeconfig (base64 encoded) used to access the target cluster.
    - name: repo-url
      description: URL of the Git repository containing the Konflux CI deployment scripts.
      default: https://github.com/konflux-ci/konflux-ci.git
    - name: repo-branch
      description: Git branch to check out when cloning the repository.
      default: main
    - name: test-name
      type: string
      description: 'The name of the test being executed.'
    - name: git-repo
      type: string
      default: 'e2e-tests'
      description: 'The name of the Git repository containing the E2E tests.'
    - name: git-url
      type: string
      default: 'https://github.com/konflux-ci/e2e-tests.git'
      description: 'The URL of the Git repository containing the E2E tests.'
    - name: git-revision
      type: string
      default: 'main'
      description: 'The revision (branch or tag) of the Git repository to checkout.'
    - name: component-image
      type: string
      description: 'Container image built from any konflux git repo.'
      default: 'none'
    - name: e2e-timeout
      description: 'Timeout value for running E2E script (cluster bootstrap + E2E tests)'
      default: '150m'
    - name: test-environment
      type: string
      description: "Name of the environment the testing should be performed in. Use 'downstream' for testing in OpenShift CI, or 'upstream' for testing in Kind cluster."
      default: 'staging'
    - name: component-name
      description: |
        The GitHub repository name of the Konflux CI component to customize (e.g., `build-service`, `release-service`).
        Used for applying image or Kubernetes manifest overrides.
      default: ''
    - name: component-image-repository
      description: |
        Overrides the container image repository for the `component-name` (e.g., `quay.io/my-org/my-custom-image`).
      default: ''
    - name: component-image-tag
      description: |
        Overrides the container image tag for the `component-name` (e.g., `latest`, `my-feature-branch`).
      default: ''
    - name: component-pr-owner
      description: |
        GitHub owner (user|org) of the fork/PR providing custom Kubernetes manifests for the `component-name`.
      default: ''
    - name: component-pr-sha
      description: |
        Commit SHA of the PR (from `component-pr-owner`) supplying custom Kubernetes manifests for the `component-name`.
      default: ''
    - name: component-pr-source-branch
      description: |
        GitHub source branch of the pull request.
      default: ''
    - name: oci-ref
      type: string
      description: Full OCI artifact reference in a format "quay.io/org/repo:tag. It's used for storing logs from the Task's Steps
    - name: oci-credentials
      type: string
      description: |
        The secret name containing credentials for container registry where the artifacts will be stored.
        The secret should contain `data.oci-storage-dockerconfigjson: <dockerconfigjson-content>`
      default: 'konflux-test-infra'

  volumes:
    - name: credentials
      secret:
        secretName: $(params.cluster-access-secret)
    - name: workdir
      emptyDir: {}
    - name: logs
      emptyDir: {}
    - name: konflux-test-infra-volume
      secret:
        secretName: $(params.oci-credentials)

  stepTemplate:
    env:
      - name: KUBECONFIG
        value: '/credentials/kubeconfig'
      - name: LOG_FILENAME
        value: '/var/log-dir/deploy-konflux-ci.log'
    volumeMounts:
      - name: credentials
        mountPath: /credentials
      - name: workdir
        mountPath: /var/workdir
      - name: logs
        mountPath: /var/log-dir/

  steps:
    - name: run-pr-check
      image: quay.io/konflux-ci/tekton-integration-catalog/utils:latest
      onError: continue
      workingDir: /var/workdir
      script: |
        #!/bin/bash
        set -euo pipefail
        # echo "cloning konflux-ui for pr-check script"
        # git clone "https://github.com/konflux-ci/konflux-ui.git" .
        # echo "listing all directories - new files"
        # echo "installing podman"
        # dnf install -y container-tools
        # echo "lising updates"
        # ls
        # podman version
        # podman info
        # # echo "running pr-check"
        # # /bin/bash -c "./pr_check.sh test"
        # exit 0
        load_envs() {
            local konflux_ci_secrets_file="/usr/local/konflux-ci-secrets"
            local konflux_infra_secrets_file="/usr/local/konflux-test-infra"

            declare -A config_envs=(
                [ENABLE_SCHEDULING_ON_MASTER_NODES]="false"
                [UNREGISTER_PAC]="true"
                [EC_DISABLE_DOWNLOAD_SERVICE]="true"
                [DEFAULT_QUAY_ORG]="redhat-appstudio-qe"
                [OCI_STORAGE_USERNAME]="$(jq -r '."quay-username"' ${konflux_infra_secrets_file}/oci-storage)"
                [OCI_STORAGE_TOKEN]="$(jq -r '."quay-token"' ${konflux_infra_secrets_file}/oci-storage)"
            )

            declare -A load_envs_from_file=(
                [DEFAULT_QUAY_ORG_TOKEN]="${konflux_ci_secrets_file}/default-quay-org-token"
                [QUAY_TOKEN]="${konflux_ci_secrets_file}/quay-token"
                [RELEASE_CATALOG_TA_QUAY_TOKEN]="${konflux_ci_secrets_file}/release-catalog-ta-quay-token"
                [QUAY_OAUTH_USER]="${konflux_ci_secrets_file}/quay-oauth-user"
                [QUAY_OAUTH_TOKEN]="${konflux_ci_secrets_file}/quay-oauth-token"
                [PYXIS_STAGE_KEY]="${konflux_ci_secrets_file}/pyxis-stage-key"
                [PYXIS_STAGE_CERT]="${konflux_ci_secrets_file}/pyxis-stage-cert"
                [ATLAS_STAGE_ACCOUNT]="${konflux_ci_secrets_file}/atlas-stage-account"
                [ATLAS_STAGE_TOKEN]="${konflux_ci_secrets_file}/atlas-stage-token"
                [ATLAS_AWS_ACCESS_KEY_ID]="${konflux_ci_secrets_file}/atlas-aws-access-key-id"
                [ATLAS_AWS_ACCESS_SECRET]="${konflux_ci_secrets_file}/atlas-aws-secret-access-key"
                [OFFLINE_TOKEN]="${konflux_ci_secrets_file}/stage_offline_token"
                [TOOLCHAIN_API_URL]="${konflux_ci_secrets_file}/stage_toolchain_api_url"
                [KEYLOAK_URL]="${konflux_ci_secrets_file}/stage_keyloak_url"
                [EXODUS_PROD_KEY]="${konflux_ci_secrets_file}/exodus_prod_key"
                [EXODUS_PROD_CERT]="${konflux_ci_secrets_file}/exodus_prod_cert"
                [CGW_USERNAME]="${konflux_ci_secrets_file}/cgw_username"
                [CGW_TOKEN]="${konflux_ci_secrets_file}/cgw_token"
                [REL_IMAGE_CONTROLLER_QUAY_ORG]="${konflux_ci_secrets_file}/release_image_controller_quay_org"
                [REL_IMAGE_CONTROLLER_QUAY_TOKEN]="${konflux_ci_secrets_file}/release_image_controller_quay_token"
                [E2E_PAC_GITHUB_APP_ID]="${konflux_ci_secrets_file}/pac-github-app-id"
                [E2E_PAC_GITHUB_APP_PRIVATE_KEY]="${konflux_ci_secrets_file}/pac-github-app-private-key"
                [PAC_GITHUB_APP_WEBHOOK_SECRET]="${konflux_ci_secrets_file}/pac-github-app-webhook-secret"
                [SLACK_BOT_TOKEN]="${konflux_ci_secrets_file}/slack-bot-token"
                [MULTI_PLATFORM_AWS_ACCESS_KEY]="${konflux_ci_secrets_file}/multi-platform-aws-access-key"
                [MULTI_PLATFORM_AWS_SECRET_ACCESS_KEY]="${konflux_ci_secrets_file}/multi-platform-aws-secret-access-key"
                [MULTI_PLATFORM_AWS_SSH_KEY]="${konflux_ci_secrets_file}/multi-platform-aws-ssh-key"
                [MULTI_PLATFORM_IBM_API_KEY]="${konflux_ci_secrets_file}/multi-platform-ibm-api-key"
                [DOCKER_IO_AUTH]="${konflux_ci_secrets_file}/docker_io"
                [GITLAB_BOT_TOKEN]="${konflux_ci_secrets_file}/gitlab-bot-token"
                [CODEBERG_BOT_TOKEN]="${konflux_ci_secrets_file}/codeberg-bot-token"
                [SMEE_CHANNEL]="${konflux_ci_secrets_file}/smee-channel"
            )

            for var in "${!config_envs[@]}"; do
                export "$var"="${config_envs[$var]}"
            done

            for var in "${!load_envs_from_file[@]}"; do
                local file="${load_envs_from_file[$var]}"
                if [[ -f "$file" ]]; then
                    export "$var"="$(<"$file")"
                else
                    log "ERROR" "Secret file for $var not found at $file"
                fi
            done
        }

        post_actions() {
            local exit_code=$?

            if [[ "$exit_code" == "124" ]]; then
                # Separate the error from the test log with new lines so it's more visible
                printf "\n\n" | tee -a "${ARTIFACT_DIR}/e2e-tests.log"
                log "ERROR" "The process for running tests timed out after $E2E_TIMEOUT" | tee -a "${ARTIFACT_DIR}/e2e-tests.log"
            fi

            exit "$exit_code"
        }

        trap post_actions EXIT

        load_envs


        timeout "$E2E_TIMEOUT" make ci/test/e2e 2>&1 | tee "${ARTIFACT_DIR}/e2e-tests.log"

    - name: secure-push-oci
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/secure-push-oci/0.1/secure-push-oci.yaml
      params:
        - name: workdir-path
          value: /var/log-dir/
        - name: oci-ref
          value: $(params.oci-ref)
        - name: credentials-volume-name
          value: konflux-test-infra-volume
    - name: fail-if-any-step-failed
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/fail-if-any-step-failed/0.1/fail-if-any-step-failed.yaml
