apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-local
spec:
  steps:
    - name: run-podman
      image: quay.io/konflux_ui_qe/konflux-ui-tests:latest
      # image: alpine
      onError: continue
      # workingDir: /var/workdir
      script: |
         #!/bin/bash
          set -euo pipefail
          cat /etc/os-release
          whoami
          ls
          echo "running pr-check"
          yarn start
          export CYPRESS_GH_TOKEN='asdf'
          ./entrypoint.sh ./e2e/tests/basic-happy-path.spec.ts
          exit 0