apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-local
spec:
  steps:
    - name: run-podman
      image: quay.io/konflux-ci/tekton-integration-catalog/utils:latest
      # image: alpine
      onError: continue
      workingDir: /var/workdir
      script: |
        #!/bin/sh
        ls
        cat /etc/os-release
        echo "installing podman"
        dnf install -y podman
        echo "current subuid"
        grep $(whoami) /etc/subuid
        grep $(whoami) /etc/subgid
        echo "updating subuid"
        usermod --add-sub-uids 100000-165535 --add-sub-gids 100000-165535 $(whoami)
        echo "new subuid"
        grep $(whoami) /etc/subuid
        grep $(whoami) /etc/subgid
        echo "changing permissions"
        chmod 0755 /usr/bin/newuidmap /usr/bin/newgidmap
        echo "run podman hello world"
        podman run hello-world