---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-main-pipeline
  namespace: abhindas-tenant
spec:
  params:
    - name: SNAPSHOT
      description: 'The JSON string representing the snapshot of the application under test.'
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - name: konflux-test-infra-secret
      description: The name of secret where testing infrastructures credentials are stored.
      type: string
    - name: cloud-credential-key
      description: The key secret from konflux-test-infra-secret where all AWS ROSA configurations are stored.
      type: string
    - name: oci-container-repo
      default: 'quay.io/konflux-test-storage/konflux-team/release-service-catalog'
      description: The ORAS container used to store all test artifacts.
  tasks:
    - name: test-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test-metadata/0.2/test-metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: test-name
          value: $(context.pipelineRun.name)
    - name: show-snapshot-data
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/abhinandan13jan/konflux-ui-test
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/Tasks/show-snapshot-data.yaml
      params:
        - name: snapshot
          value: $(params.SNAPSHOT)
    - name: check-org-membership
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/abhinandan13jan/konflux-ui-test
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/Tasks/check-org-membership.yaml
      params:
        - name: job-spec
          value: $(tasks.test-metadata.results.job-spec)
    - name: provision-kind-cluster
      runAfter:
        - check-org-membership
      when:
        - input: '$(tasks.test-metadata.results.pull-request-author)'
          operator: notin
          values: ['red-hat-konflux[bot]']
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/mapt-oci/kind-aws-spot/provision/0.2/kind-aws-provision.yaml
      params:
        - name: secret-aws-credentials
          value: mapt-kind-secret
        - name: cluster-access-secret-name
          value: kfg-$(context.pipelineRun.name)
        - name: id
          value: $(context.pipelineRun.name)
        - name: tags
          value: 'owner=konflux-devprod@redhat.com,project=Konflux,created-by=integration-pipeline,component=release-service-catalog'
        - name: debug
          value: 'false'
        - name: ownerKind
          value: PipelineRun
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
        - name: oci-ref
          value: $(params.oci-container-repo):$(context.pipelineRun.name)
        - name: credentials-secret-name
          value: $(params.konflux-test-infra-secret)
