---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-main-pipeline
  namespace: abhindas-tenant
spec:
  params:
    - name: konflux-test-infra-secret
      description: The name of secret where testing infrastructures credentials are stored.
      type: string
    - name: cloud-credential-key
      description: The key secret from konflux-test-infra-secret where all AWS ROSA configurations are stored.
      type: string
  tasks:
    - name: test-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/abhinandan13jan/konflux-ui-test
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/Tasks/test-metadata.yaml
      params:
        - name: test-secret
          value: $(params.konflux-test-infra-secret)
